eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookingservice
          uri: http://localhost:9001
          predicates:
            - Path=/bookings/**
        - id: carservice
          uri: http://localhost:9002
          predicates:
            - Path=/cars/**
        - id: flightbookingservice
          uri: http://localhost:9003
          predicates:
            - Path=/flightbooking/**
        - id: flightservice
          uri: http://localhost:9004
          predicates:
            - Path=/flights/**
        - id: userservice
          uri: http://localhost:9005
          predicates:
            - Path=/users/**